### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by ghost** [hoohack/KeepCoding#1]
在你的左旋之后为什么没有进行颜色的调整

**Comment by hoohack** [comment]
@endfighting 不需要。旋转操作是为了恢复左右子树黑高平衡，旋转之后会改变修复结点，进入下一次循环的判断。以插入修复为例，对于插入来说，旋转是因为uncle是黑色，将插入结点node的父结点parent上升到祖父结点，node == parent.right，进行左旋之后，交换node和parent的指针，node变为原来的parent，进入下一次循环。不知道有没有解释清楚，可以尝试画个图帮助理解。

**Comment by TopSpoofer** [comment]
@hoohack 痴线
